name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: beta

    #- name: Install gcloud beta components
    #  run: gcloud components install beta

    - name: Copy files to the Compute Engine instance
      run: |
        gcloud compute scp --recurse \
          ${GITHUB_WORKSPACE}/* \
          {{ env.OS_USERNAME }}@${{ env.INSTANCE_NAME }}:/home/app \
          --zone europe-west1-b \
          --project ${{ secrets.GCP_PROJECT_ID }}
      env:
        INSTANCE_NAME: instance-20240214-105617 # Replace with your actual instance name
        INSTANCE_ZONE: europe-west1-b # Replace with your actual instance zone
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Ensure this secret exists in your repo
        OS_USERNAME: ${{ secrets.OS_USERNAME }} # The OS-level username for the Compute Engine instance