name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }}

    - name: Check permissions
      run: |
        whoami
        cd ${{ github.workspace }}
        ls

    - name: Change directory to /home/app
      run: cd /home/app
      # Use this directory in subsequent steps as needed

    - name: Switch user and pull latest changes
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        cd /home/app
        pwd
        sudo su - app
        cd FarmClash
        git pull