name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONALACCESSTOKEN }} # Automatically provided by GitHub Actions

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          sudo -u app bash -c '
            cd /home/app/FarmClash &&
            git config --global credential.helper store &&
            git remote set-url origin https://${{ secrets.USERNAME }}:${{ secrets.PERSONALACCESSTOKEN }}@github.com/${{ secrets.USERNAME }}/FarmClash.git &&
            git pull
          '
        EOF