name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONALACCESSTOKEN }}

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          sudo -u app bash -c '
            # Navigate to the application directory
            cd /home/app/FarmClash
    
            # Pull the latest changes from the repository
            git pull https://github.com/SiBMs58/FarmClash.git
            
            # Activate the Python virtual environment and update dependencies
            source env/bin/activate && pip install -r requirements.txt
          
            # Deactivate the virtual environment
            deactivate
            
            # Stop the existing Gunicorn service
            sudo systemctl stop webapp
            
            # Check if a process is listening on port 5000
            port_in_use=$(sudo netstat -tuln | grep ':5000')
            
            if [ -n "$port_in_use" ]; then
                echo "Port 5000 is already in use. Attempting to stop the process..."
                
                # Find the PID of the process using port 5000
                pid=$(sudo netstat -tuln | grep ':5000' | awk '{print $7}' | cut -d'/' -f1)
            
                if [ -n "$pid" ]; then
                    # Stop the process using the PID
                    sudo kill "$pid"
                    echo "Process with PID $pid stopped."
                else
                    echo "Failed to find the PID of the process using port 5000."
                    exit 1
                fi
            else
                echo "Port 5000 is not in use."
            fi
            
            # Run the Gunicorn server
            echo "Starting the Gunicorn server..."
            source env/bin/activate
            cd /home/app/FarmClash/src/ProgDBTutor
            gunicorn --bind 0.0.0.0:5000 wsgi:app
            deactivate
            
            # Display the status of the Gunicorn service
            sudo systemctl status webapp
    
            # Check if the Gunicorn service is running and the socket file exists
            echo "Checking for the Gunicorn socket file..."
            sudo ls -l /home/app/FarmClash/src/ProgDBTutor/webapp.sock
    
            # Update and restart NGINX to apply any configuration changes
            echo "Updating NGINX configuration..."
            sudo cp /home/app/FarmClash/nginx/webapp /etc/nginx/sites-available/
            sudo ln -sf /etc/nginx/sites-available/webapp /etc/nginx/sites-enabled/
            sudo nginx -t && sudo systemctl reload nginx
          
            # Checking the webapp domain name
            echo "Checking the webapp domain name..."
            curl http://team3.ua-ppdb.me
        
            # Deactivate the virtual environment
            deactivate
          '
        EOF