name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONALACCESSTOKEN }}

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          sudo -u app bash -c '
            # Navigate to the application directory
            cd /home/app/FarmClash
            # Configure Git to use the stored credentials
            git config credential.helper store
            # Pull the latest changes from the repository
            git pull https://github.com/SiBMs58/FarmClash.git
            
            # Ensure any currently running Gunicorn processes are stopped
            cd src/ProgDBTutor
            pkill gunicorn
            sleep 5
        
            # Activate the Python virtual environment
            cd ../../ 
            source env/bin/activate
            # Install or update Python dependencies
            pip install -r requirements.txt
            # Restart the Gunicorn service to apply the changes
            # Make sure the app user has permissions to do this without entering a password
            sudo systemctl restart webapp
          '
        EOF