name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONALACCESSTOKEN }}

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          sudo -u app bash -c '
            # Navigate to the application directory
            cd /home/app/FarmClash

            # Pull the latest changes from the repository
            git pull https://github.com/SiBMs58/FarmClash.git
            
            # Activate the Python virtual environment
            source env/bin/activate
            
            # Update Python dependencies
            pip install -r requirements.txt
          '
             
          # Restart the Gunicorn service using the wsgi.py file
          # Ensure your systemd service file for Gunicorn (webapp.service) is using the wsgi module correctly
          # This command assumes the service file is properly set up to start Gunicorn with the wsgi:app command
          #sudo systemctl daemon-reload
          sudo systemctl restart webapp
          cd /home/app/FarmClash/src/ProgDBTutor
          gunicorn --bind 0.0.0.0:5000 wsgi:app


          # Display the status of the Gunicorn service
          sudo systemctl status webapp

          # Check if the Gunicorn service is running and the socket file exists
          echo "Checking for the Gunicorn socket file..."
          sudo ls -l /home/app/FarmClash/src/ProgDBTutor/webapp.sock

          # Update and restart NGINX to apply any configuration changes
          echo "Updating NGINX configuration..."
          sudo cp /home/app/FarmClash/nginx/webapp /etc/nginx/sites-available/
          sudo ln -sf /etc/nginx/sites-available/webapp /etc/nginx/sites-enabled/
          sudo nginx -t && sudo systemctl reload nginx
        
          # Checking the webapp domain name
          echo "Checking the webapp domain name..."
          curl http://team3.ua-ppdb.me
        EOF