name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONALACCESSTOKEN }}

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          sudo -u app bash -c '
            # Navigate to the application directory
            cd /home/app/FarmClash
    
            # Pull the latest changes from the repository
            git pull https://github.com/SiBMs58/FarmClash.git
            
            # Activate the Python virtual environment and update dependencies
            source env/bin/activate && pip install -r requirements.txt
          
            # Deactivate the virtual environment
            deactivate
            
            # Stop the existing Gunicorn service
            #sudo systemctl stop webapp
              
            #echo "Starting the Gunicorn server..."
            #cd /home/app/FarmClash/
            
            # Find and kill the process using port 5000, if necessary
            # This step might be redundant if Gunicorn is configured to use a Unix socket
            #PIDs=$(sudo lsof -ti:5000)
            
            
            #if [[ ! -z "$PIDs" ]]; then
            #  echo "Port 5000 is in use. Attempting to terminate..."
            #  for PID in $PIDs; do
            #    echo "Killing PID: $PID"
            #    sudo kill -9 $PID
            #  done
            #  sleep 2 # Give some time for the processes to terminate
            #fi
            
            # Assuming Gunicorn is configured to use a Unix socket
            # Start or restart the Gunicorn service instead of manually starting Gunicorn
            #echo "Starting or restarting Gunicorn service..."
            sudo systemctl restart webapp
    
            # Checking the status of the Gunicorn service
            #sudo systemctl status webapp
    
            # Ensure the Gunicorn socket file exists
            #echo "Checking for the Gunicorn socket file..."
            #sudo ls -l /home/app/FarmClash/src/ProgDBTutor/webapp.sock
    
            # Update and restart NGINX to apply any configuration changes
            #echo "Updating NGINX configuration..."
            #sudo cp /home/app/FarmClash/nginx/webapp /etc/nginx/sites-available/
            #sudo ln -sf /etc/nginx/sites-available/webapp /etc/nginx/sites-enabled/
            #sudo nginx -t && sudo systemctl reload nginx
          
            # Checking the webapp domain name
            #echo "Checking the webapp domain name..."
            #curl http://team3.ua-ppdb.me
          '
        EOF