name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Google Cloud
      run: |
        # Example: Deploy to Compute Engine
        gcloud compute instances update-container instance-20240214-105617 --container-image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image:latest --zone europe-west1-b