name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONALACCESSTOKEN }}

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          sudo -u app bash -c '
            # Navigate to the application directory
            cd /home/app/FarmClash

            # Pull the latest changes from the repository
            git pull https://github.com/SiBMs58/FarmClash.git
            
            # Activate the Python virtual environment
            source env/bin/activate
            
            # Update Python dependencies
            pip install -r requirements.txt
          '
            
          # Ensure the Gunicorn service is properly configured and enabled
          sudo systemctl daemon-reload
          sudo systemctl enable webapp
          sudo systemctl restart webapp
        
          sudo systemctl status webapp

          
          # Update and restart NGINX to apply any configuration changes
          sudo cp /home/app/FarmClash/nginx/webapp /etc/nginx/sites-available/
          sudo ln -sf /etc/nginx/sites-available/webapp /etc/nginx/sites-enabled/
          sudo nginx -t && sudo systemctl reload nginx
        EOF