name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: beta

    - name: Install gcloud beta components
      run: gcloud components install beta

    - name: Copy repository content to the Google Cloud instance
      run: |
        gcloud beta compute scp --recurse \
          ./* ${INSTANCE_NAME}:/home/app/ \
          --zone=${ZONE} \
          --project=${GCP_PROJECT_ID}
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        INSTANCE_NAME: ${{ secrets.INSTANCE_NAME }}
        ZONE: ${{ secrets.ZONE }}