name: Python application test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]  # Specify the Python version you are using

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetches the last two commits, you can adjust this as needed

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Add any other dependencies or requirements files you need to install

    - name: Run tests
      run: |
        cd src/ProgDBTutor  # Change to the source directory
        pytest tests  # Run pytest on the tests directory
