name: Python Unit Tests

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # If you have additional dependencies for testing, install them here

    - name: Run tests
      run: |
        python -m unittest discover -s src/ProgDBTutor/tests
